services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    # there's no need to expose port 80, I just expose it so that caddy will redirect http traffic to https.
    # if you are not using port 80 or port 443 other services used it, you can delete the port 80 line and change "443:443" to something else like: "8080:443" (with "8080" is your preferred port)
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    networks:
      - pterodactyl
    depends_on:
      - panel

  panel_mariadb:
    image: mariadb:latest
    container_name: panel_mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: ${MARIADB_DATABASE:-panel}
      MARIADB_USER: pterodactyl
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    volumes:
      - ./data/panel/mariadb:/var/lib/mysql
    networks:
      - pterodactyl

  panel_redis:
    image: redis:latest
    container_name: panel_redis
    restart: always
    volumes:
      - ./data/panel/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - pterodactyl

  pterodactyl_panel:
    image: ghcr.io/pterodactyl/panel:1.13.1
    container_name: pterodactyl_panel
    restart: always
    volumes:
      - ./data/panel/panel_config:/app/var/
      - ./data/panel/nginx/http.d:/etc/nginx/http.d/
      - ./panel/panel/nginx/letsencrypt:/etc/letsencrypt/
      - ./panel/panel/panel_logs:/app/storage/logs
    environment:
      # original source: https://github.com/pterodactyl/panel/blob/1.0-develop/.env.example
      # you can comment or remove some environment variables if you don't need them.
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=$APP_KEY # do not remove this
      - APP_THEME=pterodactyl
      - APP_TIMEZONE=UTC
      - APP_URL=$APP_URL # do not remove this
      - APP_LOCALE=en
      - APP_ENVIRONMENT_ONLY=true

      - LOG_CHANNEL=daily
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug

      - DB_CONNECTION=mysql # mysql method works with mariadb
      - DB_HOST=panel_mariadb # pterodactyl panel will connect to mariadb by using docker internal network, so use the the service name in here is enough
      - DB_PORT=3306
      - DB_DATABASE=${MARIADB_DATABASE:-panel} # do not remove this
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=$MARIADB_DATABASE # do not remove this

      - REDIS_HOST=panel_redis # using docker internal network to connect
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis

      - HASHIDS_SALT=${HASHIDS_SALT}
      - HASHIDS_LENGTH=8

      # if you need smtp or mail configuration, uncomment this scetion
      #- MAIL_MAILER=smtp
      #- MAIL_HOST=smtp.example.com
      #- MAIL_PORT=25
      #- MAIL_USERNAME=
      #- MAIL_PASSWORD=
      #- MAIL_ENCRYPTION=tls
      #- MAIL_FROM_ADDRESS=no-reply@example.com
      #- MAIL_FROM_NAME="Pterodactyl Panel"

  pterodactyl_wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    networks:
      - pterodactyl
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC" # change this to your preferred timezone
    volumes:
      # most of the environment variables in here use root system path (start with "/") because we give the wing access to docker socket
      # docker socket will find those paths to match with the paths inside docker image
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/run/wings:/run/wings"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

networks:
  pterodactyl:
    driver: bridge
    ipam:
      config:
        # change "40" in both subnet and gateway if your other docker containers already used it
        - subnet: 172.40.0.0/16
          gateway: 172.40.0.1
